config/routes.rb
Rails.application.routes.draw do
  resources :users_episodes_series
  resources :bookmarks
  resources :notes
  resources :episodes
  devise_for :users
  # resources :series
  # resources :seasons

  resources :series, only: [:show] do
    resources :bookmarks, only: [:create, :delete]
  end

  resources :bookmarks, only: [:show]

  resources :seasons, only: [:show]

  resources :episodes, only: [:show] do
    resources :notes, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "series#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :serie

  validates :user, presence: true
  validates :serie, presence: true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :season
  has_many :notes
  has_many :userEpisodeSerie

  validates :number, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :episode

  validates :user, presence: true
  validates :episode, presence: true
  validates :comment, length: { minimum: 2 }
  validates :note, length: { in: 0..5 }
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :serie
  mount_uploader :photo, PhotoUploader
  has_many :episodes

  validates :photo, presence: true
  validates :number, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
  has_many :seasons
  has_many :bookmarks
    has_many :userEpisodeSerie
  mount_uploader :photo, PhotoUploader

  validates :photo, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  has_many :notes
  has_many :bookmarks
  has_many :userEpisodeSerie

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/users_episodes_serie.rb
class UsersEpisodesSerie < ApplicationRecord
  belongs_to :user
  belongs_to :serie
  belongs_to :episode

  validates :user, presence: true
  validates :serie, presence: true
  validates :episode, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

    def index
      @bookmarks = Bookmark.where("user_id = ?", current_user)

    end

    def show
      @bookmarks = Bookmark.where("user_id = ?", current_user)
    end

    def new
      @serie = Serie.find(params[:series_id])
      @new_bookmark = Bookmark.new(bookmark_params)
      @new_bookmark.serie = @serie
      @new_bookmark.user = current_user

      if @new_bookmark.valid?
        @new_bookmark.save!
        flash[:notice] = "Votre série a été ajouté."
        redirect_to series_path(@serie)
      else
        render "series/show"
      end
    end

    def destroy
      @serie = Serie.find(params[:series_id])
      @delete_bookmark = Bookmark.where("serie_id = ? AND user_id = ?", @serie, current_user).delete_all
      flash[:notice] = "Votre série a été supprimé."
      redirect_to series_path(@serie)
    end

    private
    def bookmark_params
      params.permit(:serie, :user)
    end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def show
      @episode = Episode.find(params[:id])
      @season = Season.where("episode_id = ?", params[:id])
      @serie = Serie.where("season_id = ?", params[:season_id])
      @notes = Note.where("episode_id = ?", params[:id])
      @new_note = Note.new
      @users_episodes_series_view = UsersEpisodesSerie.where("user_id = ? AND serie_id = ? AND episode_id = ?", current_user, params[:series_id], params[:id])

  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!

  def create
    @episode = Episode.find(params[:episode_id])
    @new_note = Note.new(note_params)
    @new_note.episode = @episode
    @new_note.user = current_user

    if @new_note.valid?
      @new_note.save!
      flash[:notice] = "Votre commentaire a été ajouté."
      redirect_to episode_path(@episode)
    else
      render "episodes/show"
    end
  end

  private
  def note_params
    params.require(:note).permit(:episode, :user, :note, :comment)
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def show
    @season = Season.find(params[:id])
    @episodes = Episode.where("season_id = ?", params[:id])
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Serie.where("view = 'true'")
  end

  def show
    @serie = Serie.find(params[:id])
    @seasons = Season.where("serie_id = ?", params[:id])
    @new_bookmark = Bookmark.new
    @bookmark = Bookmark.where("user_id = ? AND serie_id = ?", current_user, @serie)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetaSeries</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>

  </body>
</html>

app/views/shared/_navbar.erb
<div class="collapse navbar-collapse">
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
          aria-haspopup="true" aria-expanded="false">
            Bienvenue, <%= current_user.email %>
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-user"></i> Modifier le profil
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i> Déconnexion
            <% end %>
          </li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to("Connexion", new_user_session_path) %></li>
      <li><%= link_to("Inscription", new_user_registration_path) %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="collapse navbar-collapse">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("BetaSeries", root_path, class: "navbar-brand") %>
      <%= link_to("Mes favoris", bookmarks_path, class: "navbar-brand") %>

    </div>
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
          aria-haspopup="true" aria-expanded="false">
            Bienvenue, <%= current_user.email %>
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-user"></i> Modifier le profil
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i> Déconnexion
            <% end %>
          </li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to("Connexion", new_user_session_path) %></li>
      <li><%= link_to("Inscription", new_user_registration_path) %></li>
    <% end %>
  </ul>
</div>