config/routes.rb
Rails.application.routes.draw do
  resources :users_episodes_series
  resources :bookmarks
  resources :notes
  resources :episodes
  devise_for :users
  # resources :series
  # resources :seasons

  resources :series, only: [:show] do
    resources :bookmarks, only: [:create, :delete]
  end

  resources :bookmarks, only: [:show]

  resources :seasons, only: [:show]

  resources :episodes, only: [:show] do
    resources :notes, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "series#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :serie

  validates :user, presence: true
  validates :serie, presence: true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :season
  has_many :notes
  has_many :userEpisodeSerie

  validates :number, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :episode

  validates :user, presence: true
  validates :episode, presence: true
  validates :comment, length: { minimum: 2 }
  validates :note, length: { in: 0..5 }
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :serie
  mount_uploader :photo, PhotoUploader
  has_many :episodes

  validates :photo, presence: true
  validates :number, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
  has_many :seasons
  has_many :bookmarks
    has_many :userEpisodeSerie
  mount_uploader :photo, PhotoUploader

  validates :photo, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  has_many :notes
  has_many :bookmarks
  has_many :userEpisodeSerie

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/users_episodes_serie.rb
class UsersEpisodesSerie < ApplicationRecord
  belongs_to :user
  belongs_to :serie
  belongs_to :episode

  validates :user, presence: true
  validates :serie, presence: true
  validates :episode, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

    def index
      @bookmarks = Bookmark.where("user_id = ?", current_user)

    end

    def show
      @bookmarks = Bookmark.where("user_id = ?", current_user)
    end

    def new
      @serie = Serie.find(params[:series_id])
      @new_bookmark = Bookmark.new(bookmark_params)
      @new_bookmark.serie = @serie
      @new_bookmark.user = current_user

      if @new_bookmark.valid?
        @new_bookmark.save!
        flash[:notice] = "Votre série a été ajouté."
        redirect_to series_path(@serie)
      else
        render "series/show"
      end
    end

    def destroy
      @serie = Serie.find(params[:series_id])
      @delete_bookmark = Bookmark.where("serie_id = ? AND user_id = ?", @serie, current_user).delete_all
      flash[:notice] = "Votre série a été supprimé."
      redirect_to series_path(@serie)
    end

    private
    def bookmark_params
      params.permit(:serie, :user)
    end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def show
      @episode = Episode.find(params[:id])
      @season = Season.where("episode_id = ?", params[:id])
      @serie = Serie.where("season_id = ?", params[:season_id])
      @notes = Note.where("episode_id = ?", params[:id])
      @new_note = Note.new
      @users_episodes_series_view = UsersEpisodesSerie.where("user_id = ? AND serie_id = ? AND episode_id = ?", current_user, params[:series_id], params[:id])

  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!

  def create
    @episode = Episode.find(params[:episode_id])
    @new_note = Note.new(note_params)
    @new_note.episode = @episode
    @new_note.user = current_user

    if @new_note.valid?
      @new_note.save!
      flash[:notice] = "Votre commentaire a été ajouté."
      redirect_to episode_path(@episode)
    else
      render "episodes/show"
    end
  end

  private
  def note_params
    params.require(:note).permit(:episode, :user, :note, :comment)
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def show
    @season = Season.find(params[:id])
    @episodes = Episode.where("season_id = ?", params[:id])
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Serie.where("view = 'true'")
  end

  def show
    @serie = Serie.find(params[:id])
    @seasons = Season.where("serie_id = ?", params[:id])
    @new_bookmark = Bookmark.new
    @bookmark = Bookmark.where("user_id = ? AND serie_id = ?", current_user, @serie)
  end
end

app/controllers/users_episodes_series_controller.rb
class UsersEpisodesSeriesController < ApplicationController
  before_action :authenticate_user!

  def new
    @episode = Episode.find(params[:episodes_id])
    @season = Season.where("episode_id = ?", params[:id])
    @serie = Serie.where("season_id = ?", params[:season_id])
    @new_episode_view = UsersEpisodesSerie.new(episodeView_params)
    @new_episode_view.serie = @episode.season.serie
    @new_episode_view.episode = @episode
    @new_episode_view.user = current_user

    if @new_episode_view.valid?
      @new_episode_view.save!

      redirect_to episode_path(@episode)
    else
      render "episodes/show"
    end
  end

  def destroy
    @episode = Episode.find(params[:id])
    @season = Season.where("episode_id = ?", params[:id])
    @serie = Serie.where("season_id = ?", params[:season_id])
    @delete_episode_view = UsersEpisodesSerie.where("episode_id = ? AND serie_id = ? AND user_id = ?", params[:id], params[:series_id], current_user).delete_all
      redirect_to episode_path(@episode)
  end

  private
  def episodeView_params
    params.permit(:serie, :episode, :user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/users_episodes_series_helper.rb
module UsersEpisodesSeriesHelper
end

app/views/bookmarks/_delete.html.erb
<h4>Supprimez de votre liste :</h4>
<%= simple_form_for([serie, bookmark]) do |f| %>
  <%= f.button :submit %>
<% end %>

app/views/bookmarks/_form.html.erb
<h4>Ajoutez à votre liste :</h4>
<%= simple_form_for([serie, bookmark]) do |f| %>
  <%= f.button :submit %>
<% end %>

app/views/bookmarks/index.html.erb
<%- @bookmarks.each do |bookmark| -%>
  <section class='sectionSeries'>
    <h2><%= link_to(bookmark.serie.name, series_path(bookmark.serie)) %></h2>
    <%= cl_image_tag bookmark.serie.photo, width: 199, height: 279,
                                    crop: :fill %>
  </section>
<% end %>

app/views/bookmarks/show.html.erb
<div class="">
  <h1>Saison <%=  %></h1>
  <section class="row">
    <div class="col-sm-4">
      <%=  %>
    </div>
    <div class="col-sm-8 containerEpisode">

      <% @bookmarks.each do |bookmark| %>
      <div class="episode">
          <div>
            <p class="episodeNumber">

              <%=  %>

              <br />Diffusion : <%= %>
               <br />

            </p>
          </div>
      </div>
      <% end %>
    </div>
  </section>
</div>

app/views/episodes/show.html.erb
<div class="body">
  <h1><%= @episode.name %></h1>


  <section class="row">
    <div class="col-sm-4">
      <%= @episode.description %><br /><br />
      <div class="comment-instruction">

        <% if user_signed_in? %>
          <% if @users_episodes_series_view.present? %>
            <%= link_to("Je n'ai pas vu", users_episodes_series_path(:series_id => @episode.season.serie.id, :episodes_id => @episode.id,
              :season_id => @episode.season.id), :method=>:delete, class: "btn-delete") %>
          <% else %>
            <%= link_to("J'ai vu", new_users_episodes_series_path(:series_id => @episode.season.serie.id, :episodes_id => @episode.id,
              :season_id => @episode.season.id), :action=>:create, class: "btn-delete") %>
          <% end %>
        <% else %>
          <p>Vous devez être connecté.e pour marquer comme vu cet épisode</p>
        <% end %>
        <% if user_signed_in? %>
          <%= render "notes/form", episode: @episode, note: @new_note%>
        <% else %>
          <p>Vous devez être connecté.e pour laisser un commentaire.</p>
        <% end %>
      </div>
    </div>
    

    <div class="col-sm-8">
      <div class="notes">
        <% if @episode.notes.any? %>
          <h2><%= @notes.average(:note) %>/5</h2>

          <% @episode.notes.each do |note| %>
            <%= render "notes/show", note: note %>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/notes/_average.html.erb
<section class="note">
  <blockquote>
    <%= note.average(:note) %>
  </blockquote>
</section>

app/views/notes/_form.html.erb
<h4>Ajoutez votre commentaire :</h4>
<%= simple_form_for([episode, note]) do |f| %>
  <%= f.input :comment, label: false %>
  <%= f.input :note, collection: 0..5, selected: 5, label: false %>
  <%= f.button :submit %>
<% end %>

app/views/notes/_show.html.erb
<section class="note">
  <blockquote>
    <%= note.comment %><%=  %>
  </blockquote>
  <p class="small text-right">Par <%= note.user.username %>
    le <%= l(note.created_at.to_date, format: "%d/%m/%Y") %></p>
</section>

app/views/seasons/show.html.erb
<div class="">
  <h1>Saison <%= @season.number %></h1>
  <section class="row">
    <div class="col-sm-4">
      <%= cl_image_tag(@season.photo, :cloud_name => 'dnh0iozvn', width: 199, height: 279,
                                      crop: :fill) %>
    </div>
    <div class="col-sm-8 containerEpisode">

      <% @episodes.each do |episode| %>
      <div class="episode">
          <div>
            <p class="episodeNumber">
              <%= link_to("S"+@season.number.to_s + "xE" + episode.number.to_s + " " + episode.name, episode_path(episode.id)) %>
              <%=  %>
              
              <br />Diffusion : <%= episode.diffusion %>
               <br />

            </p>
          </div>
      </div>
      <% end %>
    </div>
  </section>
</div>

app/views/series/index.html.erb
<h1>Toutes nos series</h1>

<%- @series.each do |serie| -%>
  <section class='sectionSeries'>
    <h2><%= link_to(serie.name, series_path(serie)) %></h2>
    <%= cl_image_tag serie.photo, :cloud_name => 'dnh0iozvn', width: 199, height: 279,
                                    crop: :fill%>
  </section>
<% end %>

app/views/series/show.html.erb
<div class="body">
  <h1><%= @serie.name %></h1>

  <section class="row containerLeft">
    <div class="col-sm-4 imgSerie">
      <%= cl_image_tag(@serie.photo, width: 199, height: 279, crop: :fill) %>
      <div class="bookmark">

          <% if user_signed_in? %>
            <% if @bookmark.present? %>
              <!--  -->
              <%= link_to("Je n'aime plus", bookmark_path(:series_id => @serie.id), :method=>:delete, class: "btn-delete") %>
            <% else %>
              <%= link_to("J'aime", new_bookmark_path(:series_id => @serie.id), :action=>:create, class: "btn-delete") %>
            <% end %>
          <% else %>
            <p>Vous devez être connecté.e pour aimer cette série</p>
          <% end %>
      </div>
    </div>


    <div class="col-sm-8">

      <% @seasons.each do |season| %>
      <div class="SeasonImage">
          <%= cl_image_tag(season.photo, :cloud_name => 'dnh0iozvn', width: 199, height: 279, crop: :fill) %>
          <div>
            <p class="SeasonNumber">
               <%= link_to("Saison "+season.number.to_s, season_path(season.id)) %>
            </p>
          </div>
      </div>
      <% end %>
    </div>
  </section>
</div>